## network properties
BROADCAST_NET_ADDR = 255
BROADCAST_NODE_ADDR = 255

## node properties
NODE_TX_RANGE = 100
NODE_ARRIVAL_MAX = 10
NODE_TX_POWER_MIN = 50
NODE_TX_POWER_MAX = 100
NODE_TX_POWER_DEFAULT = 100

## cluster properties
MAX_CHILD_NODES_PER_CLUSTER = 10
MINIMAL_CLUSTER_OVERLAP = False
CLUSTER_HEAD_MOBILITY = True

## simulation properties
SIM_NODE_COUNT = 50
SIM_NODE_PLACING_CELL_SIZE = 50
SIM_DURATION = 500
SIM_TIME_SCALE = 0.00001
SIM_TERRAIN_SIZE = (1400, 600)
SIM_TITLE = 'Data Collection Tree'
SIM_VISUALIZATION = True

## channel properties
PACKET_LOSS_RATIO = 0.0
CHANNEL_PROPAGATION_SPEED = 3e8

## application properties
HEARTH_BEAT_TIME_INTERVAL = 15
REPAIRING_METHOD = 'FIND_ANOTHER_PARENT'
NEIGHBOR_TABLE_SHARE_INTERVAL = 30

## routing properties
USE_MESH_ROUTING = True
MESH_ROUTING_MAX_HOPS = 3

## energy model (CC2420 radio parameters)
ENABLE_ENERGY_MODEL = True
INITIAL_ENERGY = 10000.0
MIN_ENERGY_THRESHOLD = 100.0
TX_ENERGY_PER_BIT = 0.0001
RX_ENERGY_PER_BIT = 0.00005
IDLE_ENERGY_PER_SEC = 0.01

## optimization
ENABLE_CLUSTER_OPTIMIZATION = True
OPTIMIZATION_INTERVAL = 100
OPTIMIZATION_TARGET = 'ENERGY'