## TCP-Like Reliability Settings
ENABLE_RETRANSMISSION = True
MAX_RETRIES = 3
RETRANSMIT_TIMEOUT = 3.0
ENABLE_ACK = True
RELIABLE_PACKET_TYPES = ['DATA', 'NETWORK_REQUEST']

## Multipath Routing
ENABLE_MULTIPATH_ROUTING = True
MULTIPATH_PACKET_TYPES = ['DATA']
MULTIPATH_REDUNDANCY = 2

