## Cluster Size & TX Power
MAX_CLUSTER_MEMBERS = 15
USE_UNIFORM_TX_POWER = True
TX_POWER_MIN = 100
TX_POWER_MAX = 150
TX_POWER_DEFAULT = 100
CLUSTER_TX_POWER = {}

## Packet Loss
PACKET_LOSS_RATE = 0.0
PACKET_LOSS_APPLY_TO_CONTROL = False
PACKET_LOSS_APPLY_TO_DATA = False
ENABLE_DISTANCE_DEPENDENT_LOSS = False
DISTANCE_LOSS_FACTOR = 0.1

## Minimal Overlap & CH Migration (Part 5)
ENABLE_MINIMAL_OVERLAP = True
MIN_CH_DISTANCE = 60
ENABLE_ROUTER_NODES = True
ROUTER_COLOR = (1.0, 0.5, 0.0)
MIN_ROUTER_DISTANCE_FROM_CH = 25
ROUTER_MIN_CLUSTERS = 2

## CH Handoff
ENABLE_CH_HANDOFF = False
CH_HANDOFF_LOW_ENERGY_THRESHOLD = 0.2
CH_HANDOFF_LOAD_IMBALANCE = 1.5
CH_HANDOFF_TIMEOUT = 10.0
CH_SELECTION_PREFER_HIGH_ENERGY = True
CH_SELECTION_PREFER_CENTRAL = True
CH_SELECTION_MIN_NEIGHBORS = 1
