## Node/Link Failure & Recovery (Part 6)
ENABLE_RANDOM_FAILURES = False
FAILURE_START_TIME = 600
FAILURE_INTERVAL = 200
MAX_FAILURES = 3
FAILURE_DURATION = 300
EXCLUDE_ROOT_FROM_FAILURE = True

## Orphan Detection
ORPHAN_DETECTION_INTERVAL = 30
HEARTBEAT_MISS_THRESHOLD = 3
PARENT_TIMEOUT = 60

## Network Repair
ENABLE_NETWORK_REPAIR = True
REPAIR_DELAY = 5
REPAIR_MAX_ATTEMPTS = 5
BROADCAST_ORPHAN_STATUS = True

## Visual
DEAD_NODE_COLOR = (0.5, 0.0, 0.0)

