## Simulation Properties
SIM_NODE_COUNT = 100
SIM_NODE_PLACING_CELL_SIZE = 55
SIM_DURATION = 4000
SIM_TIME_SCALE = 0.0001
SIM_TERRAIN_SIZE = (700, 700)
SIM_TITLE = 'Part 8: Structured Cluster Network'
SIM_VISUALIZATION = True
SCALE = 1
