## Logging Settings
ENABLE_LOGGING = True
LOG_NODE_FAILURES = True
LOG_NODE_RECOVERIES = True
LOG_ORPHAN_EVENTS = True
LOG_ROLE_CHANGES = True
LOG_NETWORK_JOINS = True

## Export Settings
EXPORT_TABLES = True
EXPORT_METRICS = True
METRICS_EXPORT_PATH = './'

## Metrics & Tracing
ENABLE_PACKET_TRACING = True
ENABLE_JOIN_TIME_TRACKING = True
ENABLE_DELAY_TRACKING = True

