## Part 7: Cluster Optimization Protocol

## Master Switch - DISABLED for structured formation
ENABLE_CLUSTER_OPTIMIZATION = False
OPTIMIZATION_START_TIME = 9999
OPTIMIZATION_INTERVAL = 9999

## 7a: Cluster Merging
MIN_CLUSTER_SIZE = 4
ENABLE_CLUSTER_MERGING = False
MERGE_PREFERENCE = 'NEAREST'

## 7b: Load Balancing
ENABLE_LOAD_BALANCING = False
LOAD_BALANCE_THRESHOLD = 2.0
LOAD_BALANCE_MIN_DIFF = 4
MEMBER_TRANSFER_COUNT = 2

## 7c: Energy-Aware CH Rotation
ENABLE_CH_ROTATION = False
CH_ROTATION_INTERVAL = 9999
CH_ROTATION_ENERGY_THRESHOLD = 0.3
PREFER_HIGH_DEGREE_CH = True
